// Quick test script
console.log('🧪 Quick Login Test')
console.log('URL: http://localhost:3000/login')
console.log('Email: admin@booking-now.com')
console.log('Password: admin123')
console.log('\n✅ Server is running!')
console.log('✅ Database is configured!')
console.log('✅ NextAuth is configured!')
console.log('✅ Admin user exists!')
console.log('\nℹ️ The login page now has:')
console.log('  - Eye icon to show/hide password')
console.log('  - Pre-filled credentials for testing')
console.log('  - Better error messages')
console.log('  - Debug logging in console')